### PR TITLE
OT-SplitDomainService | Moved routes from app.py to files grouped by their route uses.

### PR DESCRIPTION
**Pull request by stock-broker**
### Task Completed

- moved routes from app.y to files grouped by their route uses.
- Two Files called UserReportsService.py & UserSessionService.py
- All routes relating to reports in UserReportsService.py
- All routes relating to session in UserSesssionService.py
- Renamed app.py to server.py

### How to test
- navigate to /off-top-python/backend-services
- run `python server.py`
- open postman
- use `localhost:5000/<route-name>` to test and make sure you don't have any issues with these in postman. Let me know if you get any issues. `<route-name>` can be seen below.

- route-name list:
  - merge-user-data
  - get-user-session-duration
  - get-user-topic
  - get-users-avg-scores
  - get-users-profession-with-score
  - get-user-information
  - get-all-sessions
  - insert-session

### CODE REVIEW

File: backend-services/Services/UserReportsService.py [hunk 1]
```diff
@@ -0,0 +1,189 @@
+from flask import Blueprint
+from flask import json
+import requests
+from flask import session, request, jsonify
+from Services.UserSessionService import getAllSessions
+from datetime import datetime
+from extensions import mysql
+# userreports.py <-- userSessionDuration()
```
Comment (frlzjosh) [inline backend-services/Services/UserReportsService.py]: can we delete this comment?

File: backend-services/server.py [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+import requests
+import json
+from werkzeug.utils import cached_property # had error ImportError: cannot import name 'cached_property' from 'werkzeug' (C:\off-top-python\my-venv\lib\site-packages\werkzeug\__init__.py)
+from Services.UserReportsService import user_reports_service # blueprint
+from Services.UserSessionService import user_session_service # blueprint
+from extensions import mongo, mysql
+
+api = Api()
+app = Flask(__name__)
+# connect to MongoDB with the defaults
```
Comment (frlzjosh) [inline backend-services/server.py]: delete these comments

**Review by frlzjosh — CHANGES_REQUESTED** [review]
Everything looks good, just a few comments you gotta remove

File: backend-services/Services/UserReportsService.py (hunk 1 above)
Comment (stock-broker) [reply backend-services/Services/UserReportsService.py]: yes

File: backend-services/Services/UserReportsService.py [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+from flask import session, request, jsonify
+from Services.UserSessionService import getAllSessions
+from datetime import datetime
+from extensions import mysql
+
+user_reports_service = Blueprint("user_reports", __name__)
+
+
+@user_reports_service.route("/get-user-session-duration")
+def userSessionDuration():
```
Comment (frlzjosh) [inline backend-services/Services/UserReportsService.py:13]: this service was not migrated to this file properly. If i hit this API in postman it returns an empty instead of the expected value. I will send you a photo of the expected value in the #setup channel

**Review by frlzjosh — CHANGES_REQUESTED** [review]
Issue with get-user-session-duration

File: backend-services/server.py [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+from flask.templating import render_template
+from Models.UserSession import UserSession
+from flask_restplus import Api
+from datetime import datetime
+from datetime import timedelta
+from flask import session
+from flask_cors import CORS, cross_origin
+import requests
+import json
+from werkzeug.utils import cached_property # had error ImportError: cannot import name 'cached_property' from 'werkzeug' (C:\off-top-python\my-venv\lib\site-packages\werkzeug\__init__.py)
```
Comment (tonynguyen98) [inline backend-services/server.py:13]: Please provide documentation on which version of Werkzeug is needed in the requirements.

**Review by tonynguyen98 — CHANGES_REQUESTED** [review]
image
The build will outright not work with Werkzeug 1.0.1. Maybe you can post in the requirements which version specific pip module I need. I was able to get it to work with Werkzeug 0.15.5

**Comment by tonynguyen98** [comment]
And can you resolve any previous comment requests so I can see where this is at?

File: backend-services/Services/UserSessionService.py [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+        }
+        sessions.append(clean_session)
+        index += 1
+        all_sessions = {
+          "sessions": sessions
+        }
+    return jsonify(all_sessions)
+
+
+@user_session_service .route("/insert-session", methods=["POST"])
```
Comment (tonynguyen98) [inline backend-services/Services/UserSessionService.py:33]: It looks like this is not working properly. I am unable to hit this route in Postman
image

**Review by tonynguyen98 — CHANGES_REQUESTED** [review]
Now that I am able to get the build working, please try to look into this issue.

File: backend-services/Services/UserSessionService.py (hunk 5 above)
Comment (tonynguyen98) [reply backend-services/Services/UserSessionService.py:33]: The error was on my end, I didn't realize that this one needed parameters to be passed into this specific route. I am able to hit this route when passing in some parameters

**Comment by frlzjosh** [comment]
/insert-session was not migrated completely. The Session object was not imported into this service. Here is the error: 
Screen Shot 2020-06-16 at 12 00 18 AM

File: backend-services/Services/UserReportsService.py [hunk 6]
```diff
@@ -0,0 +1,212 @@
...
+        "transcribed_list": sorted(transcribed_list)
+    }
+    user_time_list.append(user_time)
+
+  for user in user_time_list:
+    first = user["first_transcribed_at"]
+    last = user["last_transcribed_at"]
+    transcribed_arr = user["transcribed_list"]
+
+    print(last)
```
Comment (frlzjosh) [inline backend-services/Services/UserReportsService.py]: get rid of this line

**Review by frlzjosh — APPROVED** [review]
great work!
